# Generated by Django 3.2.9 on 2021-12-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211208_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departamento'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehiculo'),
        ),
    ]
