# Generated by Django 3.2.9 on 2021-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ingresosalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosalida',
            name='estado',
            field=models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='estado',
            field=models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado'), ('SA', 'Sin asignar')], max_length=20, null=True),
        ),
    ]
