# Generated by Django 3.2.9 on 2021-12-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211208_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Sin asignar', 'Sin asignar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='estado',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salio', 'Salio')], max_length=20, null=True),
        ),
    ]
