# Generated by Django 3.2.9 on 2021-12-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211208_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionados',
            name='estacionamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.estacionamiento'),
        ),
    ]
