# Generated by Django 3.2.9 on 2021-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_estacionados_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='estacionamiento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
