# Generated by Django 3.2.9 on 2021-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_estacionamiento_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosalida',
            name='inscrito',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='estacionamiento',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='vehiculo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
