# Generated by Django 3.2.9 on 2021-12-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211210_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionados',
            old_name='vehiculo',
            new_name='patente',
        ),
        migrations.RenameField(
            model_name='ingresosalida',
            old_name='vehiculo',
            new_name='patente',
        ),
    ]
