# Generated by Django 3.2.9 on 2022-01-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_estacionamiento_patente_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='rut_propietario',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
